[build]
builder = "nixpacks"
buildCommand = "npm install && cd web/server && npm install && cd ../client && npm install && npm run build"

[deploy]
startCommand = "node web/server/index.js"
restartPolicyType = "on_failure"
